# Generated by Django 5.1.5 on 2025-01-23 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('complaint_id', models.AutoField(db_column='complaint_id', primary_key=True, serialize=False)),
                ('description', models.TextField(db_column='description')),
                ('status', models.BooleanField(db_column='status', default=True)),
            ],
            options={
                'db_table': 'complaint',
            },
        ),
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('kit_id', models.AutoField(db_column='kit_id', primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('kit_qr', models.TextField(blank=True, db_column='kit_qr', null=True)),
                ('status', models.BooleanField(blank=True, db_column='status', default=True, null=True)),
                ('allotted', models.BooleanField(blank=True, db_column='allotted', default=True, null=True)),
            ],
            options={
                'db_table': 'kit',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(db_column='staff_id', primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, db_column='type', max_length=50)),
                ('fname', models.CharField(blank=True, db_column='fname', max_length=50)),
                ('mname', models.CharField(blank=True, db_column='mname', max_length=50, null=True)),
                ('lname', models.CharField(blank=True, db_column='lname', max_length=50, null=True)),
                ('email', models.CharField(blank=True, db_column='email', max_length=100, null=True)),
                ('phno', models.CharField(blank=True, db_column='phno', max_length=50, null=True)),
                ('dept', models.CharField(blank=True, db_column='dept', max_length=50, null=True)),
                ('role', models.CharField(blank=True, db_column='role', max_length=50, null=True)),
                ('pwd', models.CharField(blank=True, db_column='pwd', max_length=50)),
                ('active', models.BooleanField(blank=True, db_column='status', default=True)),
            ],
            options={
                'db_table': 'staff',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(db_column='student_id', primary_key=True, serialize=False)),
                ('fname', models.CharField(blank=True, db_column='fname', max_length=50)),
                ('mname', models.CharField(blank=True, db_column='mname', max_length=50, null=True)),
                ('lname', models.CharField(blank=True, db_column='lname', max_length=50, null=True)),
                ('usn', models.CharField(blank=True, db_column='usn', max_length=50)),
                ('email', models.CharField(blank=True, db_column='email', max_length=50, null=True)),
                ('dept', models.CharField(blank=True, db_column='dept', max_length=50, null=True)),
                ('semester', models.IntegerField(db_column='SEMESTER', null=True)),
                ('pwd', models.CharField(blank=True, db_column='pwd', max_length=50, null=True)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('comp_id', models.AutoField(db_column='comp_id', primary_key=True, serialize=False)),
                ('comp_name', models.CharField(db_column='comp_name', max_length=250)),
                ('status', models.CharField(db_column='status', max_length=1)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('url', models.CharField(blank=True, db_column='url', max_length=255, null=True)),
                ('kit', models.ForeignKey(db_column='kit_id', on_delete=django.db.models.deletion.DO_NOTHING, to='api.kit')),
            ],
            options={
                'db_table': 'component',
            },
        ),
        migrations.CreateModel(
            name='LabTransactions',
            fields=[
                ('transaction_id', models.AutoField(db_column='transaction_id', primary_key=True, serialize=False)),
                ('lab_date', models.DateField(db_column='lab_date')),
                ('status', models.BooleanField(db_column='status', default=True)),
                ('checkin_time', models.DateTimeField(db_column='checkin_time')),
                ('checkout_time', models.DateTimeField(blank=True, db_column='checkout_time', null=True)),
                ('dept', models.CharField(blank=True, db_column='dept', max_length=50, null=True)),
                ('semester', models.IntegerField(db_column='semester', null=True)),
                ('kit', models.ForeignKey(db_column='kit_id', on_delete=django.db.models.deletion.DO_NOTHING, to='api.kit')),
                ('staff', models.ForeignKey(db_column='staff_id', on_delete=django.db.models.deletion.DO_NOTHING, to='api.staff')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.DO_NOTHING, to='api.student')),
            ],
            options={
                'db_table': 'lab_transactions',
            },
        ),
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('issue_id', models.AutoField(db_column='issue_id', primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='description', max_length=255)),
                ('status', models.CharField(db_column='status', max_length=1)),
                ('reported_on', models.DateTimeField(db_column='reported_on')),
                ('resolution', models.CharField(blank=True, db_column='resolution', max_length=255, null=True)),
                ('res_datetime', models.DateTimeField(blank=True, db_column='res_datetime', null=True)),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.component')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.complaint')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.kit')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.student')),
            ],
            options={
                'db_table': 'issues',
            },
        ),
        migrations.AddConstraint(
            model_name='component',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['G', 'D', 'O'])), name='chk_sensor_status'),
        ),
        migrations.AddConstraint(
            model_name='issues',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['O', 'C', 'S'])), name='chk_issues_status'),
        ),
    ]
