# Generated by Django 5.1.5 on 2025-01-23 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtransactions',
            name='checkin_time',
            field=models.DateTimeField(db_column='checkin_time'),
        ),
        migrations.AlterField(
            model_name='labtransactions',
            name='kit',
            field=models.ForeignKey(db_column='kit_id', on_delete=django.db.models.deletion.DO_NOTHING, to='api.kit'),
        ),
        migrations.AlterField(
            model_name='labtransactions',
            name='staff',
            field=models.ForeignKey(db_column='staff_id', on_delete=django.db.models.deletion.DO_NOTHING, to='api.staff'),
        ),
        migrations.AlterField(
            model_name='labtransactions',
            name='student',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.DO_NOTHING, to='api.student'),
        ),
    ]
